repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      args: ["--line-length", "100"]

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    files: \.py$
    args: [--profile=black]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [
        'flake8-bugbear==20.1.4',
        'flake8-logging-format==0.6.0',
        'flake8-implicit-str-concat==0.2.0',
    ]
    stages: [manual]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.942"
  hooks:
  - id: mypy
    args: ["--config-file", ".mypy.ini"]
    additional_dependencies: [types-requests, types-PyYAML, types-mock, tornado, black, pytest, gitpython, pyjwt]
    stages: [manual]

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.14.2
  hooks:
    - id: check-jsonschema
      name: "Check GitHub Workflows"
      files: ^\.github/workflows/
      types: [yaml]
      args: ["--schemafile", "https://json.schemastore.org/github-workflow"]
      stages: [manual]
